/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_rzeszut_rust_jni_JniExample */

#ifndef _Included_io_rzeszut_rust_jni_JniExample
#define _Included_io_rzeszut_rust_jni_JniExample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_rzeszut_rust_jni_JniExample
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_rzeszut_rust_jni_JniExample_sayHello(JNIEnv *,
                                                                       jclass,
                                                                       jstring);

#ifdef __cplusplus
}
#endif
#endif
